/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.generator;

import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import java.util.Spliterator;
import java.util.Spliterators;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ShedulerGenerator extends AbstractGenerator {

	private Stream<EObject> contentsStream(Resource resource) {
		return StreamSupport.stream(
				Spliterators.spliteratorUnknownSize(
						resource.getAllContents(), Spliterator.ORDERED),
				false);
	}

	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		contentsStream(resource)
				.filter(it -> it instanceof TaskPool)
				.map(it -> (TaskPool) it)
				.forEach(it -> doGenerate(it, fsa, context));
	}

	private void doGenerate(TaskPool taskPool, IFileSystemAccess2 fsa, IGeneratorContext context) {
		fsa.generateFile("sheduler.txt", taskPool.toString());
	}
}
