/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ShedulerWebModule extends AbstractShedulerWebModule {
}
