/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.validation;


import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.*;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import java.time.DateTimeException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * This class contains custom validation rules. 
 * <p>
 * Xtext calls every {@code @Check} method on every model element whose type matches the method's parameter.
 * {@code CheckType.FAST} checks run on every keystroke in the editor, the others (default: {@code NORMAL}) on save.
 * {@code error(...)} marks the model as invalid (no code generation / interpretation),
 * while {@code warning(...)} is just reported to the user.
 * <p>
 * Beware: if a check throws an exception, Xtext logs it and silently skips the remaining checks,
 * hence the try/catch blocks below.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ShedulerValidator extends AbstractShedulerValidator {
	
    // Ex 1.1: the runtime needs durations in milliseconds, as a long, which may overflow (e.g. `in 2147483647 years`)
    @Check
    public void checkRelativeTimeIsRepresentable(RelativeTime relativeTime) {
        try {
            TimeUtils.toDuration(relativeTime).toMillis(); // the runtime schedules in milliseconds
        } catch (ArithmeticException e) {
            warning("Relative time is not representable on the JVM", relativeTime, ShedulerPackage.Literals.RELATIVE_TIME__TIME_SPANS);
        }
    }

    // Ex 1.2: LocalDateTime.of throws DateTimeException for invalid dates (e.g. Feb 31) or out-of-range years,
    // and the delay from now may overflow the milliseconds a long can hold
    @Check
    public void checkAbsoluteTimeIsRepresentable(AbsoluteTime absoluteTime) {
        try {
            Duration.between(LocalDateTime.now(), TimeUtils.toLocalDateTime(absoluteTime)).toMillis();
        } catch (ArithmeticException | DateTimeException e) {
            warning("Absolute time is not representable on the JVM", absoluteTime, ShedulerPackage.Literals.ABSOLUTE_TIME__DATE);
        }
    }

    // Ex 1.3: scheduling something in the past makes little sense
    @Check
    public void checkAbsoluteTimeIsInTheFuture(AbsoluteTime absoluteTime) {
        LocalDateTime dateTime;
        try {
            dateTime = TimeUtils.toLocalDateTime(absoluteTime);
        } catch (DateTimeException e) {
            return; // already reported by checkAbsoluteTimeIsRepresentable / ensureDateIsValid / ensureClockTimeIsValid
        }
        if (!dateTime.isAfter(LocalDateTime.now())) { // slide: "in the past or in the present"
            warning("Absolute time should be in the future", absoluteTime, ShedulerPackage.Literals.ABSOLUTE_TIME__TIME);
        }
    }

    @Check(CheckType.FAST)
    public void ensureDateIsValid(Date date) {
        if (date.getYear() < 0) {
            error("Year must be positive", date, ShedulerPackage.Literals.DATE__YEAR, 0);
        }
        if (date.getMonth() < 1 || date.getMonth() > 12) {
            error("Month must be between 1 and 12", date, ShedulerPackage.Literals.DATE__MONTH, 0);
        }
        if (date.getDay() < 1 || date.getDay() > 31) {
            error("Day must be between 1 and 31", date, ShedulerPackage.Literals.DATE__DAY, 0);
        }
    }

    // Ex 1.4
    @Check(CheckType.FAST)
    public void ensureClockTimeIsValid(ClockTime clockTime) { // INT cannot be negative in the grammar
        if (clockTime.getHour() > 23) {
            error("Hour must be between 0 and 23", clockTime, ShedulerPackage.Literals.CLOCK_TIME__HOUR);
        }
        if (clockTime.getMinute() > 59) {
            error("Minute must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MINUTE);
        }
        if (clockTime.getSecond() > 59) {
            error("Second must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__SECOND);
        }
        if (clockTime.getMillisecond() > 999) {
            error("Millisecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MILLISECOND);
        }
        if (clockTime.getNanosecond() > 999) {
            error("Nanosecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__NANOSECOND);
        }
    }

    // Ex 1.5: `in 0 s` is pointless; there are no upper bounds though, as `48 hours` is a perfectly fine time span
    @Check(CheckType.FAST)
    public void ensureTimeSpanIsValid(TimeSpan timeSpan) {
        if (timeSpan.getDuration() <= 0) { // INT cannot be negative in the grammar, so this effectively catches 0
            error("Duration must be strictly positive", timeSpan, ShedulerPackage.Literals.TIME_SPAN__DURATION);
        }
    }

    // Ex 1.6: Set.add returns false if the name was already there; anonymous tasks (name == null) are skipped
    @Check(CheckType.FAST)
    public void ensureTaskNamesAreUniqueWithinPool(TaskPool pool) {
        Set<String> names = new HashSet<>();
        for (Task task : pool.getTasks()) {
            if (task.getName() != null && !names.add(task.getName())) {
                error("Repeated task ID: " + task.getName(), task, ShedulerPackage.Literals.TASK__NAME);
            }
        }
    }

    // Ex 1.7: same as above, for pools
    @Check(CheckType.FAST)
    public void ensurePoolNamesAreUniqueWithinPool(TaskPoolSet pools) {
        Set<String> names = new HashSet<>();
        for (TaskPool pool : pools.getPools()) {
            if (pool.getName() != null && !names.add(pool.getName())) {
                error("Repeated pool ID: " + pool.getName(), pool, ShedulerPackage.Literals.TASK_POOL__NAME);
            }
        }
    }

    // Ex 1.8: a dependent task runs whenever its anchor does, so a period of its own would be meaningless
    @Check(CheckType.FAST)
    public void ensureDependentTasksAreNotPeriodic(Task task) {
        if ((task.getBefore() != null || task.getAfter() != null) && task.getPeriod() != null) {
            error("Tasks scheduled before/after another task cannot be periodic", task, ShedulerPackage.Literals.TASK__PERIOD);
        }
    }

    // not requested by the exercises: the runtime works in milliseconds, so `repeat every 500 ns` would become a
    // period of 0 ms, which ScheduledExecutorService rejects with an IllegalArgumentException
    @Check
    public void ensurePeriodIsAtLeastOneMillisecond(Task task) {
        if (task.getPeriod() == null) return;
        try {
            if (TimeUtils.toDuration(task.getPeriod()).toMillis() < 1) {
                error("Period must be at least 1 millisecond", task, ShedulerPackage.Literals.TASK__PERIOD);
            }
        } catch (ArithmeticException e) {
            // reported by checkRelativeTimeIsRepresentable
        }
    }

    /*
     * Ex 5: `a after b` + `b after a` means neither task ever runs.
     * Each task has at most one anchor (before/after are alternatives in the grammar), so starting from a task and
     * following anchors either reaches a timed task (anchor == null) or loops forever: the `visited` set detects the loop.
     * Only tasks which are part of the loop get the error (current == task), not those merely leading into it.
     */
    @Check
    public void ensureNoDependencyCycles(Task task) {
        Set<Task> visited = new HashSet<>();
        for (Task current = task; current != null; current = anchorOf(current)) {
            if (!visited.add(current)) {
                if (current == task) {
                    error("Cyclic dependency: task never reaches a timed task", task,
                          task.getBefore() != null ? ShedulerPackage.Literals.TASK__BEFORE : ShedulerPackage.Literals.TASK__AFTER);
                }
                return;
            }
        }
    }

    private static Task anchorOf(Task task) {
        return task.getBefore() != null ? task.getBefore() : task.getAfter();
    }
}
