/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.validation;


import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.*;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import java.time.DateTimeException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ShedulerValidator extends AbstractShedulerValidator {
	
    @Check
    public void checkRelativeTimeIsRepresentable(RelativeTime relativeTime) {
        try {
            TimeUtils.toDuration(relativeTime).toMillis(); // the runtime schedules in milliseconds
        } catch (ArithmeticException e) {
            warning("Relative time is not representable on the JVM", relativeTime, ShedulerPackage.Literals.RELATIVE_TIME__TIME_SPANS);
        }
    }

    @Check
    public void checkAbsoluteTimeIsRepresentable(AbsoluteTime absoluteTime) {
        try {
            Duration.between(LocalDateTime.now(), TimeUtils.toLocalDateTime(absoluteTime)).toMillis();
        } catch (ArithmeticException | DateTimeException e) {
            warning("Absolute time is not representable on the JVM", absoluteTime, ShedulerPackage.Literals.ABSOLUTE_TIME__DATE);
        }
    }

    @Check
    public void checkAbsoluteTimeIsInTheFuture(AbsoluteTime absoluteTime) {
        LocalDateTime dateTime;
        try {
            dateTime = TimeUtils.toLocalDateTime(absoluteTime);
        } catch (DateTimeException e) {
            return; // already reported by checkAbsoluteTimeIsRepresentable / ensureDateIsValid / ensureClockTimeIsValid
        }
        if (!dateTime.isAfter(LocalDateTime.now())) { // slide: "in the past or in the present"
            warning("Absolute time should be in the future", absoluteTime, ShedulerPackage.Literals.ABSOLUTE_TIME__TIME);
        }
    }

    @Check(CheckType.FAST)
    public void ensureDateIsValid(Date date) {
        if (date.getYear() < 0) {
            error("Year must be positive", date, ShedulerPackage.Literals.DATE__YEAR, 0);
        }
        if (date.getMonth() < 1 || date.getMonth() > 12) {
            error("Month must be between 1 and 12", date, ShedulerPackage.Literals.DATE__MONTH, 0);
        }
        if (date.getDay() < 1 || date.getDay() > 31) {
            error("Day must be between 1 and 31", date, ShedulerPackage.Literals.DATE__DAY, 0);
        }
    }

    @Check(CheckType.FAST)
    public void ensureClockTimeIsValid(ClockTime clockTime) { // INT cannot be negative in the grammar
        if (clockTime.getHour() > 23) {
            error("Hour must be between 0 and 23", clockTime, ShedulerPackage.Literals.CLOCK_TIME__HOUR);
        }
        if (clockTime.getMinute() > 59) {
            error("Minute must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MINUTE);
        }
        if (clockTime.getSecond() > 59) {
            error("Second must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__SECOND);
        }
        if (clockTime.getMillisecond() > 999) {
            error("Millisecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MILLISECOND);
        }
        if (clockTime.getNanosecond() > 999) {
            error("Nanosecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__NANOSECOND);
        }
    }

    @Check(CheckType.FAST)
    public void ensureTimeSpanIsValid(TimeSpan timeSpan) {
        if (timeSpan.getDuration() <= 0) { // INT cannot be negative in the grammar, so this effectively catches 0
            error("Duration must be strictly positive", timeSpan, ShedulerPackage.Literals.TIME_SPAN__DURATION);
        }
    }

    @Check(CheckType.FAST)
    public void ensureTaskNamesAreUniqueWithinPool(TaskPool pool) {
        Set<String> names = new HashSet<>();
        for (Task task : pool.getTasks()) {
            if (task.getName() != null && !names.add(task.getName())) {
                error("Repeated task ID: " + task.getName(), task, ShedulerPackage.Literals.TASK__NAME);
            }
        }
    }

    @Check(CheckType.FAST)
    public void ensurePoolNamesAreUniqueWithinPool(TaskPoolSet pools) {
        Set<String> names = new HashSet<>();
        for (TaskPool pool : pools.getPools()) {
            if (pool.getName() != null && !names.add(pool.getName())) {
                error("Repeated pool ID: " + pool.getName(), pool, ShedulerPackage.Literals.TASK_POOL__NAME);
            }
        }
    }
}
