/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.validation;


import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.*;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * This class contains custom validation rules.
 * <p>
 * Xtext calls every {@code @Check} method on every model element whose type matches the method's parameter.
 * {@code CheckType.FAST} checks run on every keystroke in the editor, the others (default: {@code NORMAL}) on save.
 * {@code error(message, object, feature)} marks the model as invalid (no code generation / interpretation),
 * while {@code warning(message, object, feature)} is just reported to the user.
 * <p>
 * Beware: if a check throws an exception, Xtext logs it and silently skips the remaining checks.
 * So, never let exceptions escape from {@code @Check} methods (and do NOT throw "TODO" exceptions here).
 * <p>
 * Tests: {@code ShedulerValidatorTest}. Each test is {@code @Disabled}: remove the annotation once the rule is done.
 * <p>
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ShedulerValidator extends AbstractShedulerValidator {

    // Example rule, already implemented: use it as a reference for the others
    @Check(CheckType.FAST)
    public void ensureDateIsValid(Date date) {
        if (date.getYear() < 0) {
            error("Year must be positive", date, ShedulerPackage.Literals.DATE__YEAR, 0);
        }
        if (date.getMonth() < 1 || date.getMonth() > 12) {
            error("Month must be between 1 and 12", date, ShedulerPackage.Literals.DATE__MONTH, 0);
        }
        if (date.getDay() < 1 || date.getDay() > 31) {
            error("Day must be between 1 and 31", date, ShedulerPackage.Literals.DATE__DAY, 0);
        }
    }

    @Check
    public void checkRelativeTimeIsRepresentable(RelativeTime relativeTime) {
        // TODO Ex 1.1a: convert relativeTime into a java.time.Duration via TimeUtils.toDuration
        // TODO Ex 1.1b: the runtime will need it in milliseconds: also call .toMillis() on it
        // TODO Ex 1.1c: if any of the two throws ArithmeticException (overflow), report a warning on
        //               ShedulerPackage.Literals.RELATIVE_TIME__TIME_SPANS, whose message contains "not representable"
        //               (try it with `in 2147483647 years`)
    }

    @Check
    public void checkAbsoluteTimeIsRepresentable(AbsoluteTime absoluteTime) {
        // TODO Ex 1.2a: convert absoluteTime into a java.time.LocalDateTime via TimeUtils.toLocalDateTime
        // TODO Ex 1.2b: beware, LocalDateTime.of throws java.time.DateTimeException (NOT ArithmeticException)
        //               for invalid dates (e.g. 2030/02/31) or out-of-range years: catch it
        // TODO Ex 1.2c: the runtime turns it into a delay from now: Duration.between(LocalDateTime.now(), ...).toMillis()
        //               may overflow too (ArithmeticException)
        // TODO Ex 1.2d: in all such cases, report a warning on ShedulerPackage.Literals.ABSOLUTE_TIME__DATE,
        //               whose message contains "not representable"
    }

    @Check
    public void checkAbsoluteTimeIsInTheFuture(AbsoluteTime absoluteTime) {
        // TODO Ex 1.3a: convert absoluteTime via TimeUtils.toLocalDateTime, and simply return on DateTimeException
        //               (invalid dates are already reported by other rules)
        // TODO Ex 1.3b: if it is NOT after LocalDateTime.now() (i.e. past or present), report a warning
        //               on ShedulerPackage.Literals.ABSOLUTE_TIME__TIME, whose message contains "future"
    }

    @Check(CheckType.FAST)
    public void ensureClockTimeIsValid(ClockTime clockTime) {
        // NOTE: INT cannot be negative in the grammar, so you only need upper bounds
        // TODO Ex 1.4a: error on CLOCK_TIME__HOUR if hour > 23 (message starting with "Hour")
        // TODO Ex 1.4b: error on CLOCK_TIME__MINUTE if minute > 59
        // TODO Ex 1.4c: error on CLOCK_TIME__SECOND if second > 59
        // TODO Ex 1.4d: error on CLOCK_TIME__MILLISECOND if millisecond > 999
        // TODO Ex 1.4e: error on CLOCK_TIME__NANOSECOND if nanosecond > 999
    }

    @Check(CheckType.FAST)
    public void ensureTimeSpanIsValid(TimeSpan timeSpan) {
        // TODO Ex 1.5: error on TIME_SPAN__DURATION if the duration is zero or negative
        //              (message containing "strictly positive")
        //              NOTE: do not add upper bounds, `repeat every 48 hours` is perfectly fine
    }

    @Check(CheckType.FAST)
    public void ensureTaskNamesAreUniqueWithinPool(TaskPool pool) {
        // TODO Ex 1.6a: iterate over pool.getTasks(), skipping anonymous ones (getName() == null)
        // TODO Ex 1.6b: keep the names seen so far in a Set<String> (hint: Set.add returns false for duplicates)
        // TODO Ex 1.6c: error on the duplicate task, feature TASK__NAME, message "Repeated task ID: <name>"
    }

    @Check(CheckType.FAST)
    public void ensurePoolNamesAreUniqueWithinPool(TaskPoolSet pools) {
        // TODO Ex 1.7: same as Ex 1.6, but for pools (feature TASK_POOL__NAME, message "Repeated pool ID: <name>")
    }

    @Check(CheckType.FAST)
    public void ensureDependentTasksAreNotPeriodic(Task task) {
        // TODO Ex 1.8: error on TASK__PERIOD if the task is scheduled before/after another task
        //              (getBefore() or getAfter() not null) AND it has a period (message containing "cannot be periodic")
    }

    @Check
    public void ensurePeriodIsAtLeastOneMillisecond(Task task) {
        // TODO Ex 1.9 (bonus): the runtime works in milliseconds, so `repeat every 500 ns` becomes a period of 0 ms,
        //                      which ScheduledExecutorService rejects at run time with an IllegalArgumentException:
        //                      error on TASK__PERIOD if the period is < 1 ms (message containing "at least 1 millisecond")
        //                      Beware of ArithmeticException (already reported by Ex 1.1)
    }

    @Check
    public void ensureNoDependencyCycles(Task task) {
        // TODO Ex 5.17: `a after b` + `b after a` means neither task ever runs
        // TODO Ex 5.17a: each task has at most one anchor (its getBefore() or getAfter())
        // TODO Ex 5.17b: starting from task, follow anchors until reaching a timed task (anchor == null)...
        // TODO Ex 5.17c: ...or until you meet a task you already visited (a cycle!)
        // TODO Ex 5.17d: report an error on TASK__BEFORE or TASK__AFTER (message containing "Cyclic"),
        //                           but only if `task` itself is part of the cycle
    }
}
