/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.generator;

import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.Task;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPoolSet;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import java.io.*;
import java.util.List;
import java.util.Map;

/**
 * Generates code from your model files on save.
 * <p>
 * For a file {@code Foo.shed}, it should generate 3 Java files:
 * {@code ShedulerRuntime.java}, {@code ShedulerTask.java}, and {@code ShedulerSystem_Foo.java}
 * (cf. the "Usage example" slide for the expected shape of the latter).
 * <p>
 * Utilities inherited from {@link AbstractShedulerGenerator}:
 * {@code javaTemplateFile("X")} loads {@code src/main/resources/.../generator/X.java.template}, and
 * {@code javaTemplateFile("X", Map.of("KEY", "value"))} also replaces every {@code __KEY__} placeholder in it.
 * <p>
 * Tests: {@code ShedulerGeneratorTest} (remove {@code @Disabled} once done): it also compiles the generated code.
 * You can also try the generator via {@code ./gradlew :it.unibo.spe.mdd.sheduler:run --args=/abs/path/file.shed}.
 * <p>
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ShedulerGenerator extends AbstractShedulerGenerator {
	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		File inputFile = new File(resource.getURI().toFileString());
		TaskPoolSet taskPools = (TaskPoolSet) resource.getContents().get(0);
		// TODO Ex 3.1: the file name becomes part of a Java class name: replace chars which are not allowed there
		//              (e.g. '-' in `my-tasks.shed`; hint: regex \W)
		String inputFileName = inputFile.getName().split("\\.")[0];

		// TODO Ex 3.2: generate the runtime, i.e. the same code as class it.unibo.spe.mdd.sheduler.runtime.ShedulerRuntime
		//              (hint: there is already a copy of it in ShedulerRuntime.java.template)
		fsa.generateFile("ShedulerRuntime.java", "// TODO Ex 3.2");

		// TODO Ex 3.3: same as Ex 3.2, for ShedulerTask
		fsa.generateFile("ShedulerTask.java", "// TODO Ex 3.3");

		// TODO Ex 3.4: generate class ShedulerSystem_<inputFileName>, importing the classes from package
		//              it.unibo.spe.mdd.sheduler.runtime, plus java.time.* and java.util.concurrent.Executors
		//              (hint: write a ShedulerSystem.java.template with __PLACEHOLDERS__, and fill them via javaTemplateFile)
		// TODO Ex 3.5: its main method creates a ShedulerRuntime, wrapping Executors.newScheduledThreadPool(...),
		//              then calls one pool method per pool, see generateTaskPoolsCalls
		// TODO Ex 3.6: the class also contains the definitions of the pool methods, see generateTaskPoolsDefinitions
		fsa.generateFile("ShedulerSystem_" + inputFileName + ".java", "// TODO Ex 3.4");
	}

	// TODO Ex 3.7: name of the Java method generated for a pool, e.g. pool_myPool
	//              (anonymous pools may be named after their position in the file, e.g. pool_0)
	private String generateTaskPoolMethodName(TaskPool taskPool, int index) {
		throw new UnsupportedOperationException("TODO Ex 3.7: generate the name of the method for a pool");
	}

	// TODO Ex 3.8: one `private static void pool_X(ShedulerRuntime runtime) { ... }` method per pool,
	//              whose body is generated by generateTaskPool
	private String generateTaskPoolsDefinitions(TaskPoolSet taskPools) throws IOException {
		throw new UnsupportedOperationException("TODO Ex 3.8: generate one method per pool");
	}

	// TODO Ex 3.9: one `pool_X(runtime);` call per pool, to be put in main
	private String generateTaskPoolsCalls(TaskPoolSet taskPools) {
		throw new UnsupportedOperationException("TODO Ex 3.9: generate one method call per pool");
	}

	// TODO Ex 3.10: body of a pool method: declare one local variable per task (named by position: task0, task1, ...,
	//               as DSL names are optional, and may clash with Java keywords), via generateTask
	// TODO Ex 3.11: then, schedule each task via `runtime.schedule(taskN);`
	// TODO Ex 5.10: dependencies: in between declarations and scheduling, attach each dependent task to its anchor:
	//               `x after y` becomes `taskY.addSuccessor(taskX);`, `x before y` becomes `taskY.addPredecessor(taskX);`
	//               (hint: anchors are in the same pool, so List.indexOf gives you their position)
	// TODO Ex 5.11: dependent tasks must NOT be scheduled: only their anchors are
	private String generateTaskPool(TaskPool pool) {
		throw new UnsupportedOperationException("TODO Ex 3.10: generate the body of a pool method");
	}

	// TODO Ex 3.12: `in <relative time>` becomes `ShedulerTask taskN = ShedulerTask.in(<name>, <command>, <entrypoint>, Duration.parse("<ISO-8601>"));`
	//               (hint: TimeUtils.toDuration(...).toString() gives you the ISO-8601 text, e.g. PT5M)
	// TODO Ex 3.13: `at <absolute time>` becomes `... ShedulerTask.at(..., LocalDateTime.parse("<ISO-8601>"));`
	//               (hint: TimeUtils.toLocalDateTime(...).toString())
	// TODO Ex 3.14: `repeat every <relative time>` adds `taskN.setPeriod(Duration.parse("<ISO-8601>"));`
	// TODO Ex 3.15: name and entry point are optional in the DSL: pass a Java `null` literal when they are missing
	// TODO Ex 5.12: tasks with `before`/`after` become `... ShedulerTask.dependent(<name>, <command>, <entrypoint>);`
	private String generateTask(int i, Task task) {
		throw new UnsupportedOperationException("TODO Ex 3.12: generate the declaration of a task");
	}

	// TODO Ex 3.16: render s as a Java string literal (or `null`), escaping \ " and newlines/tabs:
	//               otherwise `command "echo \"hi\""` would produce `"echo "hi""`, which does not compile
	static String javaString(String s) {
		throw new UnsupportedOperationException("TODO Ex 3.16: render a Java string literal");
	}
}
