/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.generator;

import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.Task;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPoolSet;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import java.io.*;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ShedulerGenerator extends AbstractShedulerGenerator {
	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		File inputFile = new File(resource.getURI().toFileString());
		TaskPoolSet taskPools = (TaskPoolSet) resource.getContents().get(0);
		String inputFileName = inputFile.getName().split("\\.")[0];
		// TODO compute content of files depending on taskPools
		fsa.generateFile("generated_from_" + inputFileName + ".java", "content here");
	}

}
