/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.generator;

import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.sheduler.Task;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPoolSet;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import java.io.*;
import java.util.List;
import java.util.Map;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ShedulerGenerator extends AbstractShedulerGenerator {
	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		File inputFile = new File(resource.getURI().toFileString());
		TaskPoolSet taskPools = (TaskPoolSet) resource.getContents().get(0);
		String inputFileName = inputFile.getName().split("\\.")[0].replaceAll("\\W", "_");
		try {
			var runtimeClass = javaTemplateFile("ShedulerRuntime");
			fsa.generateFile("ShedulerRuntime.java", runtimeClass);

			var taskClass = javaTemplateFile("ShedulerTask");
			fsa.generateFile("ShedulerTask.java", taskClass);

			var systemClass = javaTemplateFile("ShedulerSystem", Map.of(
					"INPUT", inputFileName,
					"TASK_POOLS_CALLS", generateTaskPoolsCalls(taskPools),
					"TASK_POOLS_DEFS", generateTaskPoolsDefinitions(taskPools)
			));
			fsa.generateFile("ShedulerSystem_" + inputFileName + ".java", systemClass);
		} catch (IOException e) {
			throw new Error("Buggy generator: missing template.", e);
		}
	}

	private String generateTaskPoolMethodName(TaskPool taskPool, int index) {
		return "pool_" + (taskPool.getName() == null ? Integer.toString(index) : taskPool.getName());
	}

	private String generateTaskPoolsDefinitions(TaskPoolSet taskPools) throws IOException {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < taskPools.getPools().size(); i++) {
			TaskPool pool = taskPools.getPools().get(i);
			sb.append(javaTemplateFile("taskPool", Map.of(
					"ID", generateTaskPoolMethodName(pool, i),
					"TASKS", generateTaskPool(pool)
			)));
			sb.append("\n");
		}
		return sb.toString();
	}
	
	private String generateTaskPoolsCalls(TaskPoolSet taskPools) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < taskPools.getPools().size(); i++) {
			TaskPool pool = taskPools.getPools().get(i);
			sb.append(generateTaskPoolMethodName(pool, i) + "(runtime);");
			sb.append("\n");
		}
		return sb.toString();
	}
	
	private String generateTaskPool(TaskPool pool) {
		StringBuilder sb = new StringBuilder();
		List<Task> tasks = pool.getTasks();
		// 1. declare all tasks
		for (int i = 0; i < tasks.size(); i++) {
			sb.append(generateTask(i, tasks.get(i))).append("\n");
		}
		// 2. wire dependencies (before/after are pool-local, cf. ShedulerScopeProvider)
		for (int i = 0; i < tasks.size(); i++) {
			Task task = tasks.get(i);
			if (task.getAfter() != null) {
				sb.append("task").append(tasks.indexOf(task.getAfter())).append(".addSuccessor(task").append(i).append(");\n");
			} else if (task.getBefore() != null) {
				sb.append("task").append(tasks.indexOf(task.getBefore())).append(".addPredecessor(task").append(i).append(");\n");
			}
		}
		// 3. schedule anchors only (dependent tasks are triggered by their anchors)
		for (int i = 0; i < tasks.size(); i++) {
			Task task = tasks.get(i);
			if (task.getBefore() == null && task.getAfter() == null) {
				sb.append("runtime.schedule(task").append(i).append(");\n");
			}
		}
		return sb.toString();
	}

	private String generateTask(int i, Task task) {
		String args = javaString(task.getName()) + ", " + javaString(task.getCommand()) + ", " + javaString(task.getEntrypoint());
		String factory;
		if (task.getRelative() != null) {
			factory = "in(" + args + ", Duration.parse(" + javaString(TimeUtils.toDuration(task.getRelative()).toString()) + "))";
		} else if (task.getAbsolute() != null) {
			factory = "at(" + args + ", LocalDateTime.parse(" + javaString(TimeUtils.toLocalDateTime(task.getAbsolute()).toString()) + "))";
		} else {
			factory = "dependent(" + args + ")";
		}
		String code = "ShedulerTask task" + i + " = ShedulerTask." + factory + ";";
		if (task.getPeriod() != null) {
			code += "\ntask" + i + ".setPeriod(Duration.parse(" + javaString(TimeUtils.toDuration(task.getPeriod()).toString()) + "));";
		}
		return code;
	}

	/** Renders a Java string literal (or the {@code null} literal). */
	static String javaString(String s) {
		if (s == null) return "null";
		return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"")
				.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + "\"";
	}
}
