/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unibo.spe.mdd.sheduler.ShedulerRuntimeModule;
import it.unibo.spe.mdd.sheduler.ShedulerStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShedulerIdeSetup extends ShedulerStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShedulerRuntimeModule(), new ShedulerIdeModule()));
	}
	
}
