/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.scoping;


import it.unibo.spe.mdd.sheduler.sheduler.ShedulerPackage;
import it.unibo.spe.mdd.sheduler.sheduler.Task;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import java.util.Set;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ShedulerScopeProvider extends AbstractShedulerScopeProvider {

    @Override
    public IScope getScope(EObject context, EReference reference) {
        return super.getScope(context, reference);
    }
}
