/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.scoping;


import it.unibo.spe.mdd.sheduler.sheduler.ShedulerPackage;
import it.unibo.spe.mdd.sheduler.sheduler.Task;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPool;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import java.util.Set;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ShedulerScopeProvider extends AbstractShedulerScopeProvider {

    @Override
    public IScope getScope(EObject context, EReference reference) {
        // A scope is the set of candidates a cross-reference may point to (and what content assist proposes).
        // Tests: ShedulerScopingTest (remove @Disabled once done).
        // TODO Ex 2a: only handle the case where context is a Task, and reference is
        //             ShedulerPackage.Literals.TASK__AFTER or ShedulerPackage.Literals.TASK__BEFORE
        // TODO Ex 2b: find the TaskPool containing the task (hint: EcoreUtil2.getContainerOfType)
        // TODO Ex 2c: candidates are the tasks of that pool, except anonymous ones (getName() == null)...
        // TODO Ex 2d: ...and except the task itself (a task cannot be scheduled before/after itself)
        // TODO Ex 2e: wrap the candidates into an IScope via Scopes.scopeFor(...), and return it
        // otherwise, fall back to the default scoping:
        return super.getScope(context, reference);
    }
}
