/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ShedulerStandaloneSetup extends ShedulerStandaloneSetupGenerated {

	public static void doSetup() {
		new ShedulerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
