/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.tests;

import com.google.inject.Inject;
import com.google.inject.Provider;
import it.unibo.spe.mdd.sheduler.sheduler.TaskPoolSet;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.generator.GeneratorContext;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator2;
import org.eclipse.xtext.generator.InMemoryFileSystemAccess;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;

import javax.tools.ToolProvider;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(InjectionExtension.class)
@InjectWith(ShedulerInjectorProvider.class)
class ShedulerGeneratorTest {
	private static final String TIMED_TASKS = """
			  schedule task periodic { command "echo \\"quoted\\" \\\\ back" entry point "/bin/sh -c" in 5 minutes repeat every 48 hours }
			  schedule task absolute { command "echo abs" at 2099/01/01 10:00 }
			""";

	private static final String DEPENDENT_TASKS = """
			  schedule task first { command "echo first" before periodic }
			  schedule task last { command "echo last" after periodic }
			""";

	@Inject
	private ParseHelper<TaskPoolSet> parseHelper;

	@Inject
	private ValidationTestHelper validationTestHelper;

	@Inject
	private Provider<ResourceSet> resourceSetProvider;

	@Inject
	private IGenerator2 generator;

	@TempDir
	Path tempDir;

	@Test
	void timedTasks() throws Exception {
		String system = generateAndCompile("pool p {\n" + TIMED_TASKS + "}");
		assertTrue(system.contains("ShedulerTask.at(\"absolute\", \"echo abs\", null, LocalDateTime.parse(\"2099-01-01T10:00\"))"), system);
		assertTrue(system.contains("task0.setPeriod(Duration.parse(\"PT48H\"))"), system);
		assertTrue(system.contains("runtime.schedule(task0)"), system);
		assertTrue(system.contains("runtime.schedule(task1)"), system);
	}

	@Test
	void dependentTasks() throws Exception {
		String system = generateAndCompile("pool p {\n" + TIMED_TASKS + DEPENDENT_TASKS + "}");
		assertTrue(system.contains("ShedulerTask.dependent(\"first\""), system);
		assertTrue(system.contains("task0.addPredecessor(task2)"), system);
		assertTrue(system.contains("task0.addSuccessor(task3)"), system);
		assertTrue(system.contains("runtime.schedule(task0)"), system);
		assertFalse(system.contains("runtime.schedule(task2)"), system);
		assertFalse(system.contains("runtime.schedule(task3)"), system);
	}

	/** Generates code for the given model, checks that it compiles, and returns the ShedulerSystem_Sample class. */
	private String generateAndCompile(String text) throws Exception {
		TaskPoolSet model = parseHelper.parse(text, URI.createFileURI(tempDir.resolve("Sample.shed").toString()), resourceSetProvider.get());
		validationTestHelper.assertNoErrors(model);

		InMemoryFileSystemAccess fsa = new InMemoryFileSystemAccess();
		generator.doGenerate(model.eResource(), fsa, new GeneratorContext());
		Map<String, CharSequence> files = fsa.getTextFiles();

		List<String> paths = new ArrayList<>();
		for (String name : List.of("ShedulerRuntime.java", "ShedulerTask.java", "ShedulerSystem_Sample.java")) {
			CharSequence content = files.get(IFileSystemAccess.DEFAULT_OUTPUT + name);
			assertNotNull(content, name + " not generated");
			Path path = tempDir.resolve("src").resolve(name);
			Files.createDirectories(path.getParent());
			Files.writeString(path, content);
			paths.add(path.toString());
		}

		List<String> args = new ArrayList<>(List.of("-d", tempDir.resolve("out").toString()));
		args.addAll(paths);
		assertEquals(0, ToolProvider.getSystemJavaCompiler().run(null, null, null, args.toArray(String[]::new)), "generated code does not compile");
		return files.get(IFileSystemAccess.DEFAULT_OUTPUT + "ShedulerSystem_Sample.java").toString();
	}
}
