/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.ide;


/**
 * Use this class to register ide components.
 */
public class ShedulerIdeModule extends AbstractShedulerIdeModule {
}
