/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ShedulerRuntimeModule extends AbstractShedulerRuntimeModule {
}
